name: rubber
description: Rubber is an elastic bottom sheet widget with the customizable material spring animation.
version: 1.1.0
homepage: https://github.com/mcrovero/rubber

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
